CREATE TABLE IF NOT EXISTS `tbl_reservation_b_layer` (
    `id` VARCHAR(36) NOT NULL,
    `reference` VARCHAR(50) NOT NULL DEFAULT '',
    `starts_at` DATETIME NULL     DEFAULT NULL,
    `ends_at` DATETIME NULL     DEFAULT NULL,
    `status` VARCHAR(50) NOT NULL DEFAULT '',
    `booker_id` VARCHAR(36) NOT NULL DEFAULT '',
    `guest` VARCHAR(255) NOT NULL DEFAULT '',
    `guest_gender` VARCHAR(20) NOT NULL DEFAULT '',
    `guest_age` INT UNSIGNED NULL DEFAULT NULL,
    `guest_email` VARCHAR(255) NOT NULL DEFAULT '',
    `final_price_excl_tax` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    `final_price_incl_tax` DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    `duration_in_days` INT UNSIGNED NOT NULL DEFAULT 0,
    `duration_in_nights` INT UNSIGNED NOT NULL DEFAULT 0,
    `product` TEXT NULL DEFAULT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_b_layer_status` (`status`),
    KEY `idx_b_layer_booker_id` (`booker_id`),
    KEY `idx_b_layer_starts_at` (`starts_at`),
    KEY `idx_b_layer_ends_at` (`ends_at`),
    KEY `idx_b_layer_reference` (`reference`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
